# Generated by Django 5.2 on 2025-04-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='team',
        ),
        migrations.AddField(
            model_name='session',
            name='team',
            field=models.ManyToManyField(related_name='sessions', to='app.team'),
        ),
    ]
