# Generated by Django 5.0.6 on 2025-05-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vote_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
    ]
